// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatContainer: typeof import('./src/components/chatContainer.vue')['default']
    JoinModel: typeof import('./src/components/joinModel.vue')['default']
    LeftContacts: typeof import('./src/components/leftContacts.vue')['default']
    MainContainer: typeof import('./src/components/mainContainer.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NModal: typeof import('naive-ui')['NModal']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
